### ISSUE TITLE
Support for Robot Framework 4.0

### ISSUE THREAD

**Issue by xylix** [robocorp/rpaframework#105]
WHY:

Robotframework-4.0a3 introduces support for IF/ELSE syntax which we see beneficial for
RPA and generic automation use case. Compared to test automation where Robot Framework has origins in, 
RPA processes need to take various error scenarios into account and also the flow control in general may be complex. Branching operations with the current Robot Framework syntax make the code hard to read
and understand and for this IF /  ELSE support is great **improvement.**

WHAT:

List of RF4 changes in 4.0b1
We probably need to support both RF 3 & 4..
* Backwards incompatible changes
  * Output.xml differences caused by removal of criticality and addition of SKIP
    * Probably affects executors, including jupyterlab robot kernels
    * could affect log analyzer
  * Argument conversion changes, could affect RPA framework libraries
  * Libdoc spec changes, require / enable changes at documentation generation tooling
    * Argument name, type and default are stored separately. (#3578)
    * Spec files have new information such as Enum and TypedDict data types. (#3607)
    * Argument name, type and default are stored separately. (#3578)
* Start the work with alpha / pre-release so that we are ready to go
* Document Lab and VsCode restrictions.
* Warn users about Robot features that might break

Work items:
[ ] RPA Framework supports for RF 4
  [ ] Depended libraries support RF 4
[ ] Docs to support 3 & 4

**Comment by xylix** [comment]
Docgen problems:

make docs fails with

<details><summary>Stacktrace</summary>
<p>
```
Traceback (most recent call last):
  File "/Users/kerkko/Code/rpaframework/.venv/bin/docgen", line 8, in <module>
    sys.exit(run())
  File "/Users/kerkko/Code/rpaframework/.venv/lib/python3.8/site-packages/docgen/cli.py", line 151, in run
    converter.convert(lib, args.format, args.output)
  File "/Users/kerkko/Code/rpaframework/.venv/lib/python3.8/site-packages/docgen/converter.py", line 24, in convert
    converter().convert(libdoc, path)
  File "/Users/kerkko/Code/rpaframework/.venv/lib/python3.8/site-packages/docgen/converter.py", line 73, in convert
    formatter = htmlwriter.DocFormatter(
AttributeError: module 'robot.libdocpkg.htmlwriter' has no attribute 'DocFormatter'
^CError in atexit._run_exitfuncs:
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/util.py", line 277, in _run_finalizers
Process SpawnPoolWorker-14:
Process SpawnPoolWorker-15:
Process SpawnPoolWorker-9:
Process SpawnPoolWorker-10:
Process SpawnPoolWorker-7:
Process SpawnPoolWorker-8:
Process SpawnPoolWorker-11:
Process SpawnPoolWorker-16:
Process SpawnPoolWorker-6:
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-5:
Process SpawnPoolWorker-3:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-12:
    finalizer()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 689, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 674, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt
Traceback (most recent call last):
KeyboardInterrupt
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
make: *** [docs-libdoc] Error 1
(.venv)  ~/C/rpaframework (robotframework-4) [SIGINT]> /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
(.venv)  ~/C/rpaframework (robotframework-4) [SIGINT]> raceback (most recent call last):
```
</p>
</details>
The keyboardinterrupt error keeps repeating for a while.

**Comment by xylix** [comment]
Unit test failures with Robot 4:

RPA.JSON: 
```

Full Name: | Robot.Test Json.Read JSON and Update Values
-- | --
Testing larger scenario
RPA.JSON
20201209 16:37:47.008 / 20201209 16:37:47.043 / 00:00:00.035
FAIL
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```

Most likely caused by https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst#list-and-dictionary-expansion-with-item-access
