### ISSUE TITLE
RPA.Dekstop.Windows returns error while connecting over process id

### ISSUE THREAD

**Issue by u-amine** [robocorp/rpaframework#197]
When I use the Desktop.Windows library to connect a process by id, I receive following error message, while giving the id of the process.
```
Connected to:  [DB_Akkusys_2018, AKKUSYS\koepi, Admin] - Steps Explorer 
An unexpected error occurred:  'NoneType' object has no attribute 'control_type'
Traceback:  Traceback (most recent call last):
  File "WindowCommands\Windows.py", line 10, in go_to_window
    win.connect_by_pid(window["pid"])
  File "RPA\Desktop\Windows.py", line 724, in connect_by_pid
    return self.connect_by_handle(win["handle"], windowtitle)
  File "RPA\Desktop\Windows.py", line 761, in connect_by_handle
    self.refresh_window()
  File "RPA\Desktop\Windows.py", line 1984, in refresh_window
    controls, elements = self.get_window_elements()
  File "RPA\Desktop\Windows.py", line 1509, in get_window_elements
    element = self._parse_element_attributes(element=ctrl)
  File "RPA\Desktop\Windows.py", line 1670, in _parse_element_attributes
    element_dict["parent"] = attr_value.control_type
AttributeError: 'NoneType' object has no attribute 'control_type'
```

**Comment by cmin764** [comment]
`RPA.Desktop.Windows` got deprecated in favor to `RPA.Windows`, so please use the new [library](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows) instead.
