### ISSUE TITLE
RPA.Excel.Application fails with Office 2021 on Windows 11

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#271]
The object manipulation works as expected (the workbooks can be opened and have active sheets set etc.) BUT evaluating the `self.workbook` object leads to exception:

```python
>>> bool(workbook) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cmin\AppData\Local\robocorp\holotree\b1f3c244e_59f207d3\lib\site-packages\win32com\client\__init__.py", line 549, in __len__
    return self.__dict__["_dispobj_"].__len__()
  File "C:\Users\cmin\AppData\Local\robocorp\holotree\b1f3c244e_59f207d3\lib\site-packages\win32com\client\__init__.py", line 484, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Workbook instance at 0x2442358829448>' object has no attribute '__len__'
```
and this leads to a chain of the same error when `quit_application` calls `close_document` since it's registered for exit.

Solution: understand why the boolean evaluation doesn't work as before and why it leads to a `len()` (see if a 3rd-package update will solve it).

**Comment by cmin764** [comment]
Upgrading to `pywin32==302` seems to fix it. Will get a PR raised soon.
