### ISSUE TITLE
RPA.Dialogs Win10 Run as Administrator [error]

### ISSUE THREAD

**Issue by emilszymecki** [robocorp/rpaframework#306]
Hi
I have a problem with my Robots uses RPA.Dialogs when i start as Administrator  VSCode or Robocorp Assistant
I checked on 3 machines using win10 problem is the same
I tried downgrade RPA Framework but it still exists

#task,robot
`*** Settings ***
Documentation     Template robot main suite.
Library           RPA.Dialogs

*** Keywords ***
Success dialog
    Add icon    Success
    Add heading    Your orders have been processed
    Add files    *.txt
    Run dialog    title=Success

*** Tasks ***
Start
    Success dialog
`

error
`Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Emil\AppData\Local\robocorp\holotree\b1f3c244e_6cd60f16\lib\site-packages\RPA\Dialogs\dialog.py", line 86, in stop
    if self.poll():
  File "C:\Users\Emil\AppData\Local\robocorp\holotree\b1f3c244e_6cd60f16\lib\site-packages\RPA\Dialogs\dialog.py", line 111, in poll
    self._to_result(stdout, stderr)
  File "C:\Users\Emil\AppData\Local\robocorp\holotree\b1f3c244e_6cd60f16\lib\site-packages\RPA\Dialogs\dialog.py", line 173, in _to_result
    err = stderr.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 262: invalid start byte
Error: exit status 1`

**Comment by tonnitommi** [comment]
RPA.Dialogs is replaced by RPA.Assistant. Not fixing.
