### ISSUE TITLE
RPA.Excel.Application fails to open workbook

### ISSUE THREAD

**Issue by jmejia32** [robocorp/rpaframework#319]
`testing.robot`
```
*** Settings ***
Library  RPA.Desktop  WITH NAME  Desktop
Library  RPA.Excel.Application  WITH NAME  Excel

*** Keywords ***
Abrir archivo de Excel
  Excel.Open Application  visible=False
  Open Workbook  DW1048.xlsm
  # Execution fails before this line
  Run Macro  selectodo_Click
  ${PIPES_1}=  Get Clipboard Value
  Log  ${PIPES_1}
  Excel.Quit Application

*** Tasks ***
Abrir archivo de Excel
```

`$ robot testing.robot`
```python
AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library._Workbook instance at 0x501707001184>' object has no attribute '__len__'
Traceback (most recent call last):
  File "C:\Users\dviana\Documents\rpa\robot-abastecimiento\env\lib\site-packages\RPA\Excel\Application.py", line 176, in open_workbook
    self.set_active_worksheet(sheetnumber=1)
  File "C:\Users\dviana\Documents\rpa\robot-abastecimiento\env\lib\site-packages\RPA\Excel\Application.py", line 187, in set_active_worksheet
    if not self.workbook:
  File "C:\Users\dviana\Documents\rpa\robot-abastecimiento\env\lib\site-packages\win32com\client\__init__.py", line 549, in __len__
    return self.__dict__["_dispobj_"].__len__()
  File "C:\Users\dviana\Documents\rpa\robot-abastecimiento\env\lib\site-packages\win32com\client\__init__.py", line 484, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
```
**rpaframework version**: 12.1.1
**MS Office info**: Office 365 Enterprise - Version 2004 (build 12730.20270)

**Comment by cmin764** [comment]
Works if you explicitly specify the `pywin32==302` dep in your _conda.yaml_, more details on [forum](https://forum.robocorp.com/t/attributeerror-when-working-with-excel-files/1138/7?u=cosmin).

It's a WIP [fix](https://github.com/robocorp/rpaframework/pull/278) that is prioritised for this incoming week.
