### ISSUE TITLE
when library FileSystem on mac, it has a error and never import sucess

### ISSUE THREAD

**Issue by nixuewei** [robocorp/rpaframework#41]
20200813 20:31:01.984 [WARN]: Importing test library "RPA.FileSystem" failed

Traceback (most recent call last):
list index out of range
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/libraryfetcher.py", line 29, in get_import_result
    ) for kw in lib.handlers]
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/libraryfetcher.py", line 29, in <listcomp>
    ) for kw in lib.handlers]
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/libraryfetcher.py", line 40, in _parse_args
    parsed[index] = parsed[index] + '=' + str(args.defaults[value])  # DEBUG str(value)

macos Catalina 10.15.5
RIDE v2.0b1 running on Python 3.7.7. 
robotframework==3.2.1

**Comment by osrjv** [comment]
Hi, thanks for the report.

Is this the full traceback? Can you import other RPA Framework libraries?

The FileSystem library should not do anything special during the import phase, and all of the files in the traceback are related to RIDE itself, not RPA Framework.

**Comment by osrjv** [comment]
I'm closing this issue now due to lack of information, but if it's still valid please reopen it.
