### ISSUE TITLE
ImportError: cannot import name 'Browser' from partially initialized module 'RPA.Browser' (most likely due to a circular import)

### ISSUE THREAD

**Issue by andres-mestra** [robocorp/rpaframework#62]
Hello , can you help please with this errror ?

The code I'm running is this:
```python
from RPA.Browser import Browser
nav = Browser()
nav.open_available_browser("www.google.com", headless=True)
```
but print this error:
```shell
Traceback (most recent call last):
  File "robot.py", line 1, in <module>
    from RPA.Browser import Browser
  File "/home/andres/.local/lib/python3.8/site-packages/RPA/Browser.py", line 14, in <module>
    from robot.libraries.BuiltIn import BuiltIn, RobotNotRunningError
  File "/home/andres/dev/robot/robot.py", line 1, in <module>
    from RPA.Browser import Browser
ImportError: cannot import name 'Browser' from partially initialized module 'RPA.Browser' (most likely due to a circular import) (/home/andres/.local/lib/python3.8/site-packages/RPA/Browser.py)

```

**Comment by mikahanninen** [comment]
Hi. Sorry to hear about this. What is your Python version and OS ? Could you also provide the `pip list` of the installed packages ?

**Comment by andres-mestra** [comment]
hola gracias por responder,  la versión de python 3.8.5, ubuntu 20.04 tls.
```shell
pip list:

alembic                            1.1.0.dev0          
appdirs                            1.4.4               
apturl                             0.5.2               
astroid                            2.4.2               
attrs                              19.3.0              
Authlib                            0.14.3              
autopep8                           1.5.4               
Babel                              2.6.0               
backcall                           0.1.0               
bcrypt                             3.1.7               
beautifulsoup4                     4.9.3               
bleach                             3.1.5               
blinker                            1.4                 
Brlapi                             0.7.0               
cached-property                    1.5.2               
certifi                            2019.11.28          
cffi                               1.14.3              
chardet                            3.0.4               
chrome-gnome-shell                 0.0.0               
Click                              7.0                 
clipboard                          0.0.4               
colorama                           0.4.3               
command-not-found                  0.3                 
cryptography                       2.9.2               
cupshelpers                        1.0                 
cycler                             0.10.0              
dbus-python                        1.2.16              
decorator                          4.4.2               
defer                              1.0.6               
defusedxml                         0.6.0               
distro                             1.4.0 
distro-info                        0.23ubuntu1         
dnspython                          2.0.0               
duplicity                          0.8.12.0            
entrypoints                        0.3                 
et-xmlfile                         1.0.1               
exchangelib                        3.2.1               
fasteners                          0.14.1              
Flask                              1.1.1               
Flask-BabelEx                      0.9.3               
Flask-Compress                     1.4.0               
Flask-Gravatar                     0.4.2               
Flask-Login                        0.4.1               
Flask-Mail                         0.9.1               
Flask-Migrate                      2.5.2               
Flask-Paranoid                     0.2.0               
Flask-Principal                    0.4.0               
Flask-Security-Too                 3.4.2               
Flask-SQLAlchemy                   2.1                 
Flask-WTF                          0.14.2              
fpdf                               1.7.2               
furl                               2.1.0               
future                             0.18.2              
graphviz                           0.13.2              
html5lib                           1.0.1               
httplib2                           0.14.0              
idna                               2.8                 
importlib-metadata                 1.5.0     
ipykernel                          5.2.1               
ipython                            7.14.0              
ipython-genutils                   0.2.0               
ipywidgets                         6.0.0               
isodate                            0.6.0               
isort                              5.5.4               
itsdangerous                       1.1.0               
jdcal                              1.4.1               
jedi                               0.17.0              
Jinja2                             2.11.2              
joblib                             0.14.1              
json5                              0.9.4               
jsonschema                         3.2.0               
jupyter                            1.0.0               
jupyter-client                     6.1.3               
jupyter-console                    6.1.0               
jupyter-core                       4.6.3               
jupyterlab                         2.1.2               
jupyterlab-server                  1.1.3               
keyring                            18.0.1              
kiwisolver                         1.2.0               
language-selector                  0.1                 
launchpadlib                       1.10.13             
lazr.restfulclient                 0.14.2              
lazr.uri                           1.0.3               
lazy-object-proxy                  1.4.3               
ldap3                              2.4.1               
lockfile                           0.12.2              
louis                              3.12.0              
lxml                               4.5.2               
macaroonbakery                     1.3.1               
Mako                               1.1.0               
MarkupSafe                         1.1.0               
matplotlib                         3.2.1               
mccabe                             0.6.1    
mistune                            0.8.4               
monotonic                          1.5                 
more-itertools                     4.2.0               
mpl-finance                        0.10.1              
mplfinance                         0.12.6a3            
mpmath                             1.1.0               
mss                                6.0.0               
nbconvert                          5.6.1               
nbformat                           5.0.6               
netifaces                          0.10.4              
netsuitesdk                        1.7.1               
nose                               1.3.7               
notebook                           6.0.3               
notifiers                          1.2.1               
ntlm-auth                          1.5.0               
numpy                              1.18.4              
oauthlib                           3.1.0               
olefile                            0.46                
openpyxl                           3.0.5               
orderedmultidict                   1.0.1               
packaging                          20.3                
pandas                             1.0.3               
pandocfilters                      1.4.2               
paramiko                           2.6.0               
parso                              0.7.0               
passlib                            1.7.2               
pdfminer.six                       20200402            
pexpect                            4.6.0               
pickleshare                        0.7.5               
Pillow                             7.0.0               
pip                                20.0.2              
prometheus-client                  0.7.1               
prompt-toolkit                     3.0.5               
protobuf                           3.6.1               
psutil                             5.5.1               
psycopg2                           2.8.5    
ptyprocess                         0.6.0               
pyasn1                             0.4.2               
pycairo                            1.16.2              
pycodestyle                        2.6.0               
pycparser                          2.20                
pycryptodome                       3.9.8               
pycups                             1.9.73              
Pygments                           2.6.1               
PyGObject                          3.36.0              
pyinotify                          0.9.6               
PyJWT                              1.7.1               
pylint                             2.6.0               
pymacaroons                        0.13.0              
PyNaCl                             1.3.0               
pyOpenSSL                          19.0.0              
pyparsing                          2.4.7               
PyPDF2                             1.26.0              
pyperclip                          1.8.0               
pyRFC3339                          1.1                 
pyrsistent                         0.16.0              
python-apt                         2.0.0+ubuntu0.20.4.1
python-dateutil                    2.7.3               
python-debian                      0.1.36ubuntu1       
pytz                               2019.3       
pyxdg                              0.26                
PyYAML                             5.3.1               
pyzmq                              19.0.1              
qtconsole                          4.7.4               
QtPy                               1.9.0               
reportlab                          3.5.34              
requests                           2.22.0              
requests-ntlm                      1.1.0               
requests-oauthlib                  1.3.0               
requests-toolbelt                  0.9.1               
requests-unixsocket                0.2.0               
rfc3987                            1.3.8               
robotframework                     3.2.2               
robotframework-pythonlibcore       2.1.0               
robotframework-requests            0.6.6               
robotframework-seleniumlibrary     4.5.0               
robotframework-seleniumtestability 1.1.0               
rpaframework                       5.1.0               
rpaframework-core                  1.8.0               
scikit-learn                       0.23.0              
scipy                              1.4.1               
SecretStorage                      2.3.1               
selenium                           3.141.0             
Send2Trash                         1.5.0               
setuptools                         45.2.0              
simple-salesforce                  1.10.1  
simplejson                         3.16.0              
six                                1.14.0              
sklearn                            0.0                 
sortedcontainers                   2.2.2               
soupsieve                          2.0.1               
speaklater                         1.4                 
SQLAlchemy                         1.3.12              
sqlparse                           0.2.4               
sshtunnel                          0.1.4               
sympy                              1.5.1               
systemd-python                     234                 
terminado                          0.8.3               
testpath                           0.4.4               
threadpoolctl                      2.0.0               
toml                               0.10.1              
tornado                            6.0.4               
tqdm                               4.50.1              
traitlets                          4.3.3               
tweepy                             3.9.0               
tzlocal                            2.1                 
ubuntu-advantage-tools             20.3                
ubuntu-drivers-common              0.0.0               
ufw                                0.36                
unattended-upgrades                0.1                 
urllib3                            1.25.8              
usb-creator                        0.3.7               
wadllib                            1.3.3               
wcwidth                            0.1.9               
webdrivermanager                   0.9.0         
webencodings                       0.5.1               
Werkzeug                           0.16.1              
wheel                              0.34.2              
widgetsnbextension                 2.0.0               
wrapt                              1.12.1              
WTForms                            2.2.1               
xkit                               0.0.0               
xlrd                               1.2.0               
xlutils                            2.0.0               
xlwt                               1.3.0               
zeep                               3.4.0               
zipp                               1.0.0 

```

**Comment by mikahanninen** [comment]
The problem is actually your file name, `robot.py`, which gets mixed up (for some reason) with `robotframework`s script command robot.py. If you rename your file then it should work just fine.

**Comment by osrjv** [comment]
I'm closing this issue now due to lack of activity, but if the fix mentioned above does not work, please reopen it.
